name: Deploy dev
on:
  push:
    branches: ['main']
  workflow_dispatch:
jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quorumcyber/npm-login-and-install@main
        with:
          repo: 'INSERT_REPO_NAME'
          settings: ${{ secrets.PR_LOCAL_SETTINGS }}
          token: ${{ secrets.NPM_TOKEN }}
      - name: Check Formatting
        run: npm run format:check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quorumcyber/npm-login-and-install@main
        with:
          repo: 'INSERT_REPO_NAME'
          settings: ${{ secrets.PR_LOCAL_SETTINGS }}
          token: ${{ secrets.NPM_TOKEN }}
      - name: ESLint
        run: npm run lint
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quorumcyber/npm-login-and-install@main
        with:
          repo: 'INSERT_REPO_NAME'
          settings: ${{ secrets.PR_LOCAL_SETTINGS }}
          token: ${{ secrets.NPM_TOKEN }}
      - name: Typecheck
        run: npm run typecheck
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quorumcyber/npm-login-and-install@main
        with:
          repo: 'INSERT_REPO_NAME'
          settings: ${{ secrets.PR_LOCAL_SETTINGS }}
          token: ${{ secrets.NPM_TOKEN }}
      - name: Test
        run: npm run coverage
      - if: ${{ github.base_ref == 'main' }}
        name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  deploy-dev:
    runs-on: ubuntu-latest
    needs: [formatting-check, lint, typecheck, test]
    environment:
      name: dev
      url: https://INSERT_DEV_APP_NAME.azurewebsites.net
    steps:
      - uses: actions/checkout@v3
      - uses: quorumcyber/npm-login-and-install@main
        with:
          repo: 'INSERT_REPO_NAME'
          settings: ${{ secrets.PR_LOCAL_SETTINGS }}
          token: ${{ secrets.NPM_TOKEN }}
      - name: Build dev
        run: npm run build
      - name: Zip build
        run: zip -r build.zip .
      - name: Deploy dev
        uses: Azure/functions-action@v1
        with:
          app-name: INSERT_DEV_APP_NAME
          publish-profile: ${{ secrets.INSERT_DEV_PUBLISH_PROFILE_NAME }}
          package: ./build.zip
