name: Deploy staging
on:
  push:
    branches: ['staging']
  workflow_dispatch:
jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quorumcyber/npm-login-and-install@main
        with:
          repo: 'INSERT_REPO_NAME'
          settings: ${{ secrets.PR_LOCAL_SETTINGS }}
          token: ${{ secrets.NPM_TOKEN }}
      - name: Check Formatting
        run: npm run format:check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quorumcyber/npm-login-and-install@main
        with:
          repo: 'INSERT_REPO_NAME'
          settings: ${{ secrets.PR_LOCAL_SETTINGS }}
          token: ${{ secrets.NPM_TOKEN }}
      - name: ESLint
        run: npm run lint
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quorumcyber/npm-login-and-install@main
        with:
          repo: 'INSERT_REPO_NAME'
          settings: ${{ secrets.PR_LOCAL_SETTINGS }}
          token: ${{ secrets.NPM_TOKEN }}
      - name: Typecheck
        run: npm run typecheck
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quorumcyber/npm-login-and-install@main
        with:
          repo: 'INSERT_REPO_NAME'
          settings: ${{ secrets.PR_LOCAL_SETTINGS }}
          token: ${{ secrets.NPM_TOKEN }}
      - name: Test
        run: npm run coverage
  deploy-staging:
    runs-on: ubuntu-latest
    needs: [formatting-check, lint, typecheck, test]
    environment:
      name: staging
      url: https://INSERT_STG_APP_NAME.azurewebsites.net
    steps:
      - uses: actions/checkout@v3
      - uses: quorumcyber/npm-login-and-install@main
        with:
          repo: 'INSERT_REPO_NAME'
          settings: ${{ secrets.PR_LOCAL_SETTINGS }}
          token: ${{ secrets.NPM_TOKEN }}
      - name: Build staging
        run: npm run build
      - name: Zip build
        run: zip -r build.zip .
      - name: Deploy staging
        uses: Azure/functions-action@v1
        with:
          app-name: INSERT_STG_APP_NAME
          publish-profile: ${{ secrets.INSERT_STG_PUBLISH_PROFILE_NAME }}
          package: ./build.zip
